### ISSUE TITLE
FATE/EXTELLA - Notes

### ISSUE THREAD

**Issue by marcussacana** [RGBA-CRT/LSPK-Extracter#1]
I tried dump the fate/extella [Steam ver] files, and all files over the lzz have a zlib compression.
And he crash after extract a big part of the archive.

**Comment by RGBA-CRT** [comment]
(I cannot read/write english well)
Ummm... I can not try it because I don't have that game.
This program is designed to handle with big endianness, problems may arise in that Steam game (for Intel CPU). Also, exception handling is not programmed.
Is it possible to display directory information? (/v option)
Is it possible to process only deployment? (/e option)
And what kind of message do they display?

**Comment by a1batross** [comment]
Wow, I'm not alone here. 

Extractor is still unpacking data(I also wonder about file formats), not crashed yet. 
I don't know how to compile ActiveBasic code, so even there is really endianness-related problem, I can't fix it.

**Comment by a1batross** [comment]
```
            [File,26103,78E264E5,262KB]CS15_star00_004_M.dds
            [File,26104,37B50CF4,262KB]CS15_star00_005_M.dds
            [File,26105,E64CB4C7,262KB]CS15_star00_006_M.dds
            [File,26106,B8D25EF8,131KB]CS15_star01_000_M.dds
            [File,26107,B6E6CB7D,131KB]CS15_star02_000_M.dds
            [File,26108,4F4A4C93,524KB]CS15_star03_000_M.dds
            [File,26109,8B067FBE,131KB]CS15_stone00_000_M.dds
            [File,26110,FD5493ED,131KB]CS15_sun00_000_M.dds
            [File,26111,04F81403,131KB]CS15_sun01_000_M.dds
            [File,26112,48D21C85,524KB]CS15_SV1600_WP_03_000_M.dds
            [File,26113,48A02C1A,131KB]CS15_SV1600_WP100_A_000_M.dds
            [File,26114,2B71123B,131KB]CS15_SV1600_WP200_A_000_M.dds
            [File,26115,A23A643A,131KB]CS15_SV200_wp00_000_M.dds
            [File,26116,CD7A8586,065KB]CS15_sward_glow00_000_M.dds
            [File,26117,34D60268,065KB]CS15_sward_glow01_000_M.dds
Segmentation fault
```

DDS files which I got is invalid. Can't decompress. "file" command shows that this is just a "data", nothing more.

I can try post here a small archive with a DLC, maybe it can help.

**Comment by RGBA-CRT** [comment]
Thank you for reply! It seems that it is okay to processed in big endian.

.DDS may be DirectX's file, is not it? 
Could you show me the head 32byte of the DDS file with a binary editor?
As marcussacana says, it compressed by zlib. It may be able to decompress with 7zip etc.
Regarding the crash, it seems like another simple reason. I will check it sometime.
ActiveBasic can get from [here](https://www.activebasic.com/ab4_download.html). Open .abp file with ProjectEditor.exe and execute with F2 key.

**Comment by a1batross** [comment]
openssl zlib can't decompress it. 7Zip, gunzip or else says it's not a zlib compressed.

The first 32 bytes.
```
$ head -c32 orig.dds | xxd
00000000: 5c6a 2bb3 5938 1063 23fe cf8e 2357 743f  \j+.Y8.c#...#Wt?
00000010: 4b26 6289 c619 7e8b f974 d27f bf76 d20d  K&b...~..t...v..
```

Paint.NET says it's does not appear as DDS image.

**Comment by a1batross** [comment]
From dlc0000.pk:
There is two different DDS files with same names in different folders: "texture" and "texture12". 
DDS is the only format, which I recognized and can try to open. The other file formats "mdl" and "mds"(seems a model texture) are unknown to me.

```
$ head -c32 ../dlc0000/resource/target/win/texture/ch2d_CH00_body_02.dds | xxd
00000000: 78da ecbd 0f5c 5475 beff ff61 1061 c009  x....\Tu...a.a..
00000010: 2a49 efef babb 78d7 1141 27a4 7530 db4a  *I....x..A'.u0.J

$ head -c32 ../dlc0000/resource/target/win/texture12/ch2d_CH00_body_02.dds | xxd
00000000: 78da ecbd 0d5c 53e7 d93f 7e27 e125 2146  x....\S..?~'.%!F
00000010: 6227 95ba 56c3 2a22 2802 4e2c 7655 826d  b'..V.*"(.N,vU.m
```
Interesting, first 32 bits are the same. 


UPD: Yay. Processed these two files with "openssl zlib" and got this cutie in image editor. [link](https://pp.userapi.com/c639331/v639331455/3477f/oCbZIzE0mP4.jpg)

**Comment by RGBA-CRT** [comment]
I fixed some bugs. I hope the crash problem will be solved.

I could not find a file format using the magic number "5c 6a".
So may the address calculation of the PK file incorrect.
(However, there are cases where it succeeds like that cute screenshot. I can't really understand.)
In that case I will give up because I can't confirm that.

**Comment by a1batross** [comment]
@RGBA-CRT ok, fine, I will check it out.

What about adding zlib decompress stage? I will try it by myself, but don't guarantee that everything will work. ActiveBasic seems to be very "local" and I can't find any documentation in English. Maybe I will just add external program, running after DSDecomp on Fate/Extella files. It seems easier to me. %)

UPD: Unpacked more than 30k files. Seems to be fixed. 
UPD2: Yes, it fixed. Program finished unpacking successfully. ^_^

**Comment by marcussacana** [comment]
i decompressed with the offzip... 
a1batross, a hint, you don't need repack to update a file
Open the "\resource\common\boot_config.ini"
and update the packfilefirst to false
`PackFileFirst	true` to `PackFileFirst	false`

After this just place a file in the same extracted struct of folders, in the extracted struct you see a "resource" directory, you can merge with the original "Resource" directory to read update files.

Thanks, it's all, i think...

**Comment by a1batross** [comment]
@marcussacana thanks, but I already looked in this file, where I have disabled "PowerMode" and increased "FPS" cap. :)

Now F/E is running in fullspeed on my PC

**Comment by RGBA-CRT** [comment]
I'm glad it solved it.
I was late but added zlib decompression function.

@a1batross Thank you for testing full unpacking.

**Comment by a1batross** [comment]
```
$ openssl.exe zlib -d < ch2d_CH00_body_00.dds > test.dds
26100:error:29065064:lib(41):BIO_ZLIB_READ:zlib inflate error:c_zlib.c:548:zlib error:data error

$ ./DSDecmp.exe ch2d_CH00_body_00.dds
Could not decompress ch2d_CH00_body_00.dds; no matching compression method found.

$ head -c32 ch2d_CH00_body_00.dds | xxd
00000000: 1ae3 47dc 621a 1c70 864e 9571 2300 8020  ..G.b..p.N.q#..
00000010: 45ab 300b 4632 57df 96d2 59ca 6a2d ae73  E.0.F2W...Y.j-.s
```

Some files are not zlib compressed and isn't being decompressed by DSDecmp, any ideas?

**Comment by marcussacana** [comment]
try decompress with offzip, maybe?

**Comment by a1batross** [comment]
Nope, offzip says, that this file(and many other in "textures" folder) are not in zip format. 

File: https://transfer.sh/eKj5R/ch2d_CH00_body_00.dds

**Comment by RGBA-CRT** [comment]
That file is strange. Perhaps it may be due to a bug in the program or an unresolved file format.

In lastest version, the file information is displayed in detail at the time of expansion.
> Example: [File, 008, 0x004EDEFF, 123DED11, 12KB, cmp] sample.txt

From the left are ["File", pkh index, pk offset, filepath hash, file size, compress or raw].

Also added a tool to display file information in the test directory.
Usage:
 + pkh.exe xxx.pkh> xxx.pkh.txt
 + pfs.exe xxx.pfs> xxx.pfs.txt

They display all the information of the pfs, pkh file, so you may know something.
For example, open a pk file directly and look at the offset address location. If there is 0x78 in the periphery, it is the magic number of zlib, and it is the correct starting offset.

**Comment by marcussacana** [comment]
.pk at 0x0009C9D8: AC A7 D9 F4 4C 17
.pk at 0x4D6B3340: 38 30 41 45 CD CC
[pkh & pfs info.zip](https://github.com/RGBA-CRT/LSPK-Extracter/files/1185291/pkh.pfs.info.zip)

**Comment by RGBA-CRT** [comment]
```
lspk info:
	fs file id, pk offset, path hash, size,com,filename
   	[File,25120,0xB23BFDA0,D4C5CBBD,1048KB,cmp]ch2d_CH00_body_00.dds

pfs info:
	file, id,    filename
	[File,25120]ch2d_CH00_body_00.dds

pfs string table:
	string id,string offset,filename
	[25398] 0x0009C9D8 = ch2d_CH00_body_00.dds

pkh info:
	File No.26324
	 Unknown  : D4C5CBBD
	 PK Offset: B23BFDA0
	 decompressed size : 00100080
	 compressed size   : 00031DD5
```	 
note: To access pkh info, search for "path hash" of pfs as "unknown" of pkh. Each File ID is a different thing.

So, Please check .pk's 0xB23BFD80~0xB23BFDCF.

**Comment by marcussacana** [comment]
.pk at 0xB23BFD80
```
83 A2 67 20 1F 2D 02 D4 B2 EF 41 19 33 26 C2 73
FD 7D 10 06 00 00 00 00 00 00 00 00 00 00 00 00
78 DA EC BD 0F 5C 53 F7 BD FF FF 21 14 21 60 0A
DD A4 FA BD 3F B7 D2 D5 88 A0 11 D9 0C D6 DE B6
62 B7 FE A3 B5 45 6A 12 CA 28 A4 F4 B6 B5 58
```
![https://my.mixtape.moe/wlhtdf.png](https://my.mixtape.moe/wlhtdf.png)

**Comment by RGBA-CRT** [comment]
There seems to be data in zlib format in 0xB23BFDA0 of the pk file.

We have to compare the extracted file from .pk's 0xB23BFDA0-B24BFE20 with the binary editor and expanded file with LSPK-Extracter's /e option.
If the files gave a difference, bugs in the program.

If they have no difference, unzip the file extracted by the binary editor with zlib.bat.
If the decompressed file is truly dds file format, the problem will be solved by bugfix.

**Comment by a1batross** [comment]
Re-extracted all archive with "/e" option. No difference. :(

**Comment by RGBA-CRT** [comment]
@a1batross The decompressed ch2d_CH00_body_00.dds by "openssl zlib" command is dds image file?
Or is it a file with header "1A E3 47 ..."?  If so, did zlib not display any error messages?

**Comment by a1batross** [comment]
@RGBA-CRT it's the same file, with same header, I posted here. "openssl zlib" and "offzip" says it's not a zlib compressed file.

Interesting thing. "pk-unpack.exe" creates a file named "B23BFDA0.txt", it's header:
```
00000000: 233c 66c7 193d 1f31 b83d 19ad 23bc 66c7  #<f..=.1.=..#.f.
00000010: 193d 1f31 b83d 0000 0000 44a5 32bb 683b  .=.1.=....D.2.h;
```

It's totally DIFFERENT from ch2d_CH00_body_00.dds. And still does not contain any compressed data.

**Comment by a1batross** [comment]
Meanwhile, QuickBMS script found on xentax forum works and decompresses automatically.

**Comment by RGBA-CRT** [comment]
Well..., I will review the program.
It may be helpful to have a raw ch2d_CH00_body_00.dds. Continuation of ↓.
```
78 DA EC BD 0F 5C 53 F7 BD FF FF 21 14 21 60 0A
DD A4 FA BD 3F B7 D2 D5 88 A0 11 D9 0C D6 DE B6
```
Is that QuickBMS here? http://zenhax.com/viewtopic.php?t=2183

**Comment by a1batross** [comment]
Yes, this script worked flawlessly. 

Nor pk-unpack, nor extracter can't produce valid files for half of files, but when you look by offset, you find file(78 DA bytes, etc). It's strange.

**Comment by TheAnimeDemon** [comment]
Sorry for being uninformed, but what would be the most simple guide to extracting the pk file at this point?

**Comment by RGBA-CRT** [comment]
@TheAnimeDemon It is most certain to use QuickBMS script now. You can expand it by opening the script in QuickBMS and opening the PK file.

**Comment by RGBA-CRT** [comment]
I rewrote most of the codes.
Probably the bug has fixed.
Please try it if you like.
