### ISSUE TITLE
Works for Soul Sacrifice Delta, possible to recompress archive?

### ISSUE THREAD

**Issue by loktar00** [RGBA-CRT/LSPK-Extracter#4]
Works perfectly for Soul Sacrifice Delta, I was able to extract the files in order to view textures/text/models/etc.

Could be added to the readme that this also works for SSD.

Also is there any work, or way to re compress the files into the archive after modifying them? This would allow for game mods for Soul Sacrifice Delta.

**Comment by RGBA-CRT** [comment]
Sorry for the late reply.

Thank you for test with Soul Sacrifice Delta. I added text to readme.

Also, sorry, there is no re-compress function at the moment. However, it is not difficult technically. I might implement it in the future.

**Comment by loktar00** [comment]
@RGBA-CRT oh no problem thanks for the reply! I thought about adding a PR but wasn't sure if you wanted that in this repo.

Thanks for the awesome work it allowed me to do some 3d prints of some of my favorite characters!
