### ISSUE TITLE
Guidance on Editing .gly Font Files

### ISSUE THREAD

**Issue by Kyoumachi** [RGBA-CRT/LSPK-Extracter#6]
Greetings! I have been utilizing the LSPK-Extractor tool for the purpose of extracting data from the archive.pfs file while working on modifying the fonts in IA/VT Colorful. I would like to express my satisfaction with its efficiency and ease of use. In the process of working with this tool, I have encountered multiple .gly font files contained within the archive.pfs:

```
IA_out_all0.gly
IA_out_all_B0.gly
elder_default_font0.gly
elder_default_font2.gly
elder_default_font1.gly
IA_out_all_B1.gly
IA_out_all1.gly
elder_default_font3.gly
elder_title_font_G0.gly
elder_normal_font.gly
font_02_01.gly
elder_number_font.gly
```

I'm interested in modifying these .gly files but am unsure about the best approach and the technical details involved. I'd really appreciate any help you could provide. Specifically, I'd like to learn more about:

- The structure, properties, and unique characteristics of the .gly file format that I should consider while editing.

- Recommended tools, software, or libraries for editing .gly font files, taking into account their features, compatibility, and potential limitations.

- Resources such as documentation, or examples that demonstrate working with and modifying .gly files, including step-by-step instructions, best practices, and common challenges to be aware of during the editing process.

I'd be grateful for any information or advice you can offer on editing .gly font files. Thanks in advance for your help, and for the great work you've done creating LSPK-Extractor!

**Comment by RGBA-CRT** [comment]
Sorry for the delay in responding. Thank you for using my tools. I am glad you commented.

Now, about the GLY file, unfortunately I don't have any information about it.

I can only give you some general information...
First, please find out if that file is a commonly distributed file format. If not, find out if anyone is analyzing it. If you are lucky, maybe tools available. Check the contents in a binary editor and search by magic number or distinctive text.
If that doesn't work, you'll have to analyze the format yourself. If it's a recent game, it's probably outline fonts. ttf, otf formats and implementations may be helpful.

Sorry I can't help you. Thanks.

**Comment by Kyoumachi** [comment]
Thank you for your guidance. It's unclear whether the .gly file is a standard format, but I'll investigate. If there are no dedicated tools, I'll attempt to decipher it independently, possibly using a hex editor or reverse engineering techniques. The idea that the files could be outline fonts, such as ttf or otf formats, is also a consideration, although I'm uncertain about this. Despite these uncertainties, your tool has been instrumental in my work. I appreciate it.

**Comment by RGBA-CRT** [comment]
Good luck!
